### ISSUE TITLE
No height / moving sensor updates

### ISSUE THREAD

**Issue by noxhirsch** [j5lien/esphome-idasen-desk-controller#9] opened 2021-02-17 21:17 UTC
The height and moving sensors don't update their values in Home Assistant. The height sensor always shows 14cm and the moving sensor "not moving" - everything else seems to work perfectly fine.

My config is exactly the example code from README.md (exept the names) and my log doesn't show anything weird:

<details>
  <summary>ESPHome Log</summary>
  
  ```
[21:29:07][C][idasen_desk_controller:096]: Idasen Desk Controller:
[21:29:07][C][idasen_desk_controller:097]:   Mac address: XX:XX:XX:XX:XX:XX
[21:29:07][C][idasen_desk_controller:098]:   Desk height 'AZ Desk Workstation Height'
[21:29:07][C][idasen_desk_controller:098]:     Unit of Measurement: 'cm'
[21:29:07][C][idasen_desk_controller:098]:     Accuracy Decimals: 0
[21:29:07][C][idasen_desk_controller:098]:     Icon: 'mdi:arrow-up-down'
[21:29:07][C][idasen_desk_controller:099]:   Desk moving 'AZ Desk Workstation Moving'
[21:29:07][C][idasen_desk_controller:099]:     Device Class: 'moving'
[21:29:07][C][idasen_desk_controller:100]:   Desk connection 'AZ Desk Workstation Connection'
[21:29:07][C][idasen_desk_controller:100]:     Device Class: 'connectivity'
[21:29:07][C][idasen_desk_controller:101]:   Desk 'AZ Desk Workstation'
[21:29:07][C][idasen_desk_controller:109]: Start scanning devices...
[21:29:07][C][idasen_desk_controller:052]: BLE Device found: Name: Desk Caro, Address: XXXXXX, txPower: -8
[21:29:07][C][idasen_desk_controller:052]: BLE Device found: Name: , Address: 192.168.XX.XX, manufacturer data: 4c001005471c7e6b36, txPower: 12
[21:29:07][C][idasen_desk_controller:052]: BLE Device found: Name: Desk Nico, Address: 192.168.XX.XX, txPower: -8



[21:40:46][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:46][D][cover:080]:   Position: 0%
[21:40:46][D][idasen_desk_controller:180]: Cover control - START - position 0.000000 - target 0 - current 53
[21:40:46][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:40:46][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:46][D][cover:076]:   Command: STOP
[21:40:46][D][idasen_desk_controller:191]: Cover control - STOP
[21:40:49][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:49][D][cover:080]:   Position: 0%
[21:40:49][D][idasen_desk_controller:180]: Cover control - START - position 0.000000 - target 0 - current 53
[21:40:49][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:49][D][cover:076]:   Command: STOP
[21:40:49][D][idasen_desk_controller:191]: Cover control - STOP
[21:40:49][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:49][D][cover:080]:   Position: 0%
[21:40:49][D][idasen_desk_controller:180]: Cover control - START - position 0.000000 - target 0 - current 53
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 52 to 0
[21:40:50][D][idasen_desk_controller:209]: Update Desk - Move from 52 to 0
[21:40:51][D][idasen_desk_controller:209]: Update Desk - Move from 51 to 0
[21:40:51][D][idasen_desk_controller:209]: Update Desk - Move from 51 to 0
[21:40:51][D][idasen_desk_controller:209]: Update Desk - Move from 50 to 0
[21:40:51][D][idasen_desk_controller:209]: Update Desk - Move from 50 to 0
[21:40:51][D][idasen_desk_controller:209]: Update Desk - Move from 49 to 0
[21:40:51][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:51][D][cover:076]:   Command: STOP
[21:40:51][D][idasen_desk_controller:191]: Cover control - STOP
[21:40:52][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:52][D][cover:080]:   Position: 100%
[21:40:52][D][idasen_desk_controller:180]: Cover control - START - position 1.000000 - target 65 - current 48
[21:40:52][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 65
[21:40:52][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 49 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 49 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 49 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 49 to 65
[21:40:53][D][idasen_desk_controller:209]: Update Desk - Move from 50 to 65
[21:40:54][D][idasen_desk_controller:209]: Update Desk - Move from 50 to 65
[21:40:54][D][idasen_desk_controller:209]: Update Desk - Move from 51 to 65
[21:40:54][D][idasen_desk_controller:209]: Update Desk - Move from 51 to 65
[21:40:54][D][idasen_desk_controller:209]: Update Desk - Move from 51 to 65
[21:40:54][D][idasen_desk_controller:209]: Update Desk - Move from 52 to 65
[21:40:54][D][idasen_desk_controller:209]: Update Desk - Move from 52 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 55 to 65
[21:40:55][D][idasen_desk_controller:209]: Update Desk - Move from 55 to 65
[21:40:56][D][idasen_desk_controller:209]: Update Desk - Move from 56 to 65
[21:40:56][D][idasen_desk_controller:209]: Update Desk - Move from 56 to 65
[21:40:56][D][idasen_desk_controller:209]: Update Desk - Move from 56 to 65
[21:40:56][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:40:56][D][cover:076]:   Command: STOP
[21:40:56][D][idasen_desk_controller:191]: Cover control - STOP
[21:41:03][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:41:03][D][cover:080]:   Position: 0%
[21:41:03][D][idasen_desk_controller:180]: Cover control - START - position 0.000000 - target 0 - current 57
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 57 to 0
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 57 to 0
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 57 to 0
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 57 to 0
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 57 to 0
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 56 to 0
[21:41:04][D][idasen_desk_controller:209]: Update Desk - Move from 56 to 0
[21:41:05][D][idasen_desk_controller:209]: Update Desk - Move from 56 to 0
[21:41:05][D][idasen_desk_controller:209]: Update Desk - Move from 55 to 0
[21:41:05][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:41:05][D][cover:076]:   Command: STOP
[21:41:05][D][idasen_desk_controller:191]: Cover control - STOP
[21:41:35][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:41:35][D][cover:080]:   Position: 0%
[21:41:35][D][idasen_desk_controller:180]: Cover control - START - position 0.000000 - target 0 - current 54
[21:41:35][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 0
[21:41:35][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 0
[21:41:35][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 0
[21:41:35][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 0
[21:41:35][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 0
[21:41:35][D][idasen_desk_controller:209]: Update Desk - Move from 54 to 0
[21:41:36][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:41:36][D][idasen_desk_controller:209]: Update Desk - Move from 53 to 0
[21:41:36][D][idasen_desk_controller:209]: Update Desk - Move from 52 to 0
[21:41:36][D][idasen_desk_controller:209]: Update Desk - Move from 52 to 0
[21:41:36][D][idasen_desk_controller:209]: Update Desk - Move from 51 to 0
[21:41:36][D][idasen_desk_controller:209]: Update Desk - Move from 50 to 0
[21:41:37][D][idasen_desk_controller:209]: Update Desk - Move from 50 to 0
[21:41:37][D][idasen_desk_controller:209]: Update Desk - Move from 49 to 0
[21:41:37][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:41:37][D][cover:076]:   Command: STOP
[21:41:37][D][idasen_desk_controller:191]: Cover control - STOP
[21:41:39][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:41:39][D][cover:080]:   Position: 71%
[21:41:39][D][idasen_desk_controller:180]: Cover control - START - position 0.710000 - target 46 - current 48
[21:41:39][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:39][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:39][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:39][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:39][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:39][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:40][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:40][D][idasen_desk_controller:209]: Update Desk - Move from 48 to 46
[21:41:40][D][idasen_desk_controller:209]: Update Desk - Move from 47 to 46
[21:41:40][D][idasen_desk_controller:209]: Update Desk - Move from 47 to 46
[21:41:40][D][idasen_desk_controller:204]: Update Desk - target reached
[21:41:47][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:41:47][D][cover:080]:   Position: 22%
[21:41:47][D][idasen_desk_controller:180]: Cover control - START - position 0.220000 - target 14 - current 46
[21:41:47][D][idasen_desk_controller:209]: Update Desk - Move from 46 to 14
[21:41:47][D][idasen_desk_controller:209]: Update Desk - Move from 46 to 14
[21:41:47][D][idasen_desk_controller:209]: Update Desk - Move from 46 to 14
[21:41:47][D][idasen_desk_controller:209]: Update Desk - Move from 45 to 14
[21:41:47][D][idasen_desk_controller:209]: Update Desk - Move from 45 to 14
[21:41:47][D][idasen_desk_controller:209]: Update Desk - Move from 45 to 14
[21:41:48][D][idasen_desk_controller:209]: Update Desk - Move from 45 to 14
[21:41:48][D][idasen_desk_controller:209]: Update Desk - Move from 44 to 14
[21:41:48][D][idasen_desk_controller:209]: Update Desk - Move from 44 to 14
[21:41:48][D][idasen_desk_controller:209]: Update Desk - Move from 43 to 14
[21:41:48][D][idasen_desk_controller:209]: Update Desk - Move from 43 to 14
[21:41:48][D][idasen_desk_controller:209]: Update Desk - Move from 42 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 42 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 41 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 40 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 40 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 39 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 39 to 14
[21:41:49][D][idasen_desk_controller:209]: Update Desk - Move from 38 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 38 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 37 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 37 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 36 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 35 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 35 to 14
[21:41:50][D][idasen_desk_controller:209]: Update Desk - Move from 34 to 14
[21:41:51][D][idasen_desk_controller:209]: Update Desk - Move from 34 to 14
[21:41:51][D][idasen_desk_controller:209]: Update Desk - Move from 33 to 14
[21:41:51][D][idasen_desk_controller:209]: Update Desk - Move from 32 to 14
[21:41:51][D][idasen_desk_controller:209]: Update Desk - Move from 32 to 14
[21:41:51][D][idasen_desk_controller:209]: Update Desk - Move from 31 to 14
[21:41:51][D][idasen_desk_controller:209]: Update Desk - Move from 31 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 30 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 30 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 29 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 29 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 28 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 27 to 14
[21:41:52][D][idasen_desk_controller:209]: Update Desk - Move from 27 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 26 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 26 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 25 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 24 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 24 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 23 to 14
[21:41:53][D][idasen_desk_controller:209]: Update Desk - Move from 23 to 14
[21:41:54][D][idasen_desk_controller:209]: Update Desk - Move from 22 to 14
[21:41:54][D][idasen_desk_controller:209]: Update Desk - Move from 22 to 14
[21:41:54][D][idasen_desk_controller:209]: Update Desk - Move from 21 to 14
[21:41:54][D][idasen_desk_controller:209]: Update Desk - Move from 21 to 14
[21:41:54][D][idasen_desk_controller:209]: Update Desk - Move from 20 to 14
[21:41:54][D][idasen_desk_controller:209]: Update Desk - Move from 19 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 19 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 18 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 18 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 17 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 17 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 16 to 14
[21:41:55][D][idasen_desk_controller:209]: Update Desk - Move from 15 to 14
[21:41:56][D][idasen_desk_controller:209]: Update Desk - Move from 15 to 14
[21:41:56][D][idasen_desk_controller:204]: Update Desk - target reached
[21:42:15][D][api:067]: Disconnecting Home Assistant 2021.2.3 ()
[21:42:44][D][cover:072]: 'AZ Desk Workstation' - Setting
[21:42:44][D][cover:080]:   Position: 22%
[21:42:44][D][idasen_desk_controller:180]: Cover control - START - position 0.220000 - target 14 - current 14
  ```

</details>

Do you have an idea, what else I could look for?

EDIT: Today I installed a second controller for another Idasen desk on another ESP32 with the same problem - so I can at least rule the desk and the ESP32.
The height sensor seems to update on every "reboot" of the ESP32

**Comment by spyfly** [comment] 2021-02-18 19:47
I am experiencing the same issue.

**Comment by mountainsandcode** [comment] 2021-02-20 14:18
Can confirm this issue, too. The current_position attribute of the cover is also static

**Comment by mountainsandcode** [comment] 2021-02-20 14:23
Appears to be a duplicate of #2, but I can confirm this is an issue with the latest master

**Comment by j5lien** [comment] 2021-02-20 14:43
Do you find the log `Register notification callback`  when connecting to the desk ?
```
[14:38:13][C][idasen_desk_controller:137]: Register notification callback on output characteristic.
[14:38:13][C][idasen_desk_controller:143]: Retrieve control remote characteristic.
[14:38:13][E][BLERemoteCharacteristic.cpp:274] retrieveDescriptors(): esp_ble_gattc_get_all_descr: Unknown
[14:38:13][C][idasen_desk_controller:148]: Success connecting client to device
```

I'm not sure why but it doesn't seem to work at first.

**Comment by noxhirsch** [comment] 2021-02-20 15:10
@j5lien Yes, here's the log:
```
[16:05:07][C][idasen_desk_controller:109]: Start scanning devices...
[16:05:07][C][idasen_desk_controller:052]: BLE Device found: Name: , Address: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX, serviceUUID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[16:05:07][C][idasen_desk_controller:052]: BLE Device found: Name: Desk Nico, Address: XXXXXXXXXXXXXXXXXXXXXXX, txPower: -8
[16:05:07][C][idasen_desk_controller:119]: Connecting client to device XXXXXXXXXXXXXXXXXXXXXXX, 
[16:05:07][D][binary_sensor:036]: 'AZ Desk Workstation Connection': Sending state ON
[16:05:07][C][idasen_desk_controller:129]: Retrieve input remote characteristic.
[16:05:08][E][BLERemoteCharacteristic.cpp:274] retrieveDescriptors(): esp_ble_gattc_get_all_descr: Unknown
[16:05:08][C][idasen_desk_controller:134]: Retrieve output remote characteristic.
[16:05:08][E][BLERemoteCharacteristic.cpp:274] retrieveDescriptors(): esp_ble_gattc_get_all_descr: Unknown
[16:05:08][E][BLERemoteCharacteristic.cpp:274] retrieveDescriptors(): esp_ble_gattc_get_all_descr: Unknown
[16:05:08][C][idasen_desk_controller:137]: Register notification callback on output characteristic.
[16:05:08][C][idasen_desk_controller:143]: Retrieve control remote characteristic.
[16:05:08][E][BLERemoteCharacteristic.cpp:274] retrieveDescriptors(): esp_ble_gattc_get_all_descr: Unknown
[16:05:08][C][idasen_desk_controller:148]: Success connecting client to device
[16:05:08][D][api.connection:604]: Client 'Home Assistant 2021.2.3 (XXXXXXXXX)' connected successfully!
[16:05:13][D][binary_sensor:036]: 'AZ Desk Workstation Moving': Sending state OFF
[16:05:13][D][sensor:092]: 'AZ Desk Workstation Height': Sending state 143.00000 mm with 0 decimals of accuracy
[16:05:13][D][cover:152]: 'AZ Desk Workstation' - Publishing:
[16:05:13][D][cover:155]:   Position: 22%
[16:05:13][D][cover:168]:   Current Operation: IDLE
```

**Comment by j5lien** [comment] 2021-02-20 15:29
So the callback is well registered but isn't called when the desk is moving 🤔

**Comment by mountainsandcode** [comment] 2021-02-22 17:57
When trying to setup a script myself I had issues getting callbacks to work - I think they may work differently than for some other LINAK desks but I’m not sure.

As a temporary workaround, can you manually update the position after it has completed moving? That would solve a big part of the problem for me

**Comment by mountainsandcode** [comment] 2021-04-13 08:25
@noxhirsch @spyfly You may want to try out the code from #12 to confirm whether this also fixes the issues for you - I'm having no issues using that code with bluetooth_callback set to False.

**Comment by noxhirsch** [comment] 2021-04-13 17:39
@mountainsandcode For me it's working with `bluetooth_callback: false`, too 👍

**Closed as completed** 2021-04-14 15:20 UTC
